import sqlite3
db = sqlite3.connect('development.sqlite3')
db.execute("CREATE TABLE tasks (id INTEGER PRIMARY KEY, name CHAR(255) NOT NULL)")
db.execute("INSERT INTO tasks (name) VALUES ('bread')")
db.execute("INSERT INTO tasks (name) VALUES ('cheese')")
db.execute("INSERT INTO tasks (name) VALUES ('grapes')")
db.execute("INSERT INTO tasks (name) VALUES ('cake')")
db.execute("INSERT INTO tasks (name) VALUES ('soda')")
db.execute("INSERT INTO tasks (name) VALUES ('bread')")
db.execute("INSERT INTO tasks (name) VALUES ('cheese')")
db.execute("INSERT INTO tasks (name) VALUES ('grapes')")
db.execute("INSERT INTO tasks (name) VALUES ('cake')")
db.execute("INSERT INTO tasks (name) VALUES ('soda')")
db.execute("INSERT INTO tasks (name) VALUES ('bread')")
db.execute("INSERT INTO tasks (name) VALUES ('cheese')")
db.execute("INSERT INTO tasks (name) VALUES ('grapes')")
db.execute("INSERT INTO tasks (name) VALUES ('cake')")
db.execute("INSERT INTO tasks (name) VALUES ('soda')")
db.commit()
